name: Bash
language: shell
os: linux
dist: xenial
'on':
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review
    paths:
      - Main/ripple.sh
      - Main/tmux.sh
jobs:
  lint:
    runs-on: ubuntu-latest
    container: 'debian:stable'
    steps:
      - name: Installing dependencies..
        run: >
          # Sync repos

          # Check for git

          if ! apt list --installed 2>/dev/null | grep -qP "^git\/stable.*";
          then
            # Check if we can install git
            if ! apt list | grep -qP "^git\/stable.*"; then
              apt update
            elif apt list | grep -qP "^git\/stable.*"; then
              true
            else
              exit 255
            fi
            # Install git
            apt install -y git
          elif apt list --installed 2>/dev/null | grep -qP "^git\/stable.*";
          then
            true
          else
            exit 255
          fi

          # Check for shellcheck

          if ! apt list --installed 2>/dev/null | grep -qP
          "^shellcheck\s{1}-.*"; then
            # Check if we can install shellcheck
            if ! apt list | grep -qP "^shellcheck\s{1}-.*"; then
              apt update
            elif apt list | grep -qP "^shellcheck\s{1}-.*"; then
              true
            else
              exit 255
            fi
            # Install shellcheck
            apt install -y shellcheck
          elif apt list --installed 2>/dev/null | grep -qP
          "^shellcheck\s{1}-.*"; then
            true
          else
            exit 255
          fi
      - name: Checking for execution error(s)..
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"/Main
          ./ripple.sh -h | exit 1
      - name: Checking for shellcheck error(s)..
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"/Main
          shellcheck --external-sources --shell=bash ripple.sh | exit 1
