name: ripple-test

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [ready_for_review]
    paths:
    - 'Main/ripple'

jobs:
  # Test runtime on debian
  runtime-debian:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - name: Pulling git dir..
        uses: actions/checkout@v2
      - name: Processing files..
        # Make sure that bash is used
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"

          # Process files
          ## NOTICE: Do not use for loop to avoid pitfall https://mywiki.wooledge.org/BashPitfalls#pf1
          git --git-dir="$GITHUB_WORKSPACE/.git" ls-files -z -- '*.sh' | while IFS= read -rd '' file; do
              printf 'Starting runtime test of %s\n' "$file"
              "$file" --install-ripple || exit 12
          done
